/*
 * generated by Xtext 2.20.0
 */
package de.grammarcraft.epsilon.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class EpsilonUiModule extends AbstractEpsilonUiModule {

	public EpsilonUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
