/*
 * generated by Xtext 2.21.0
 */
package de.grammarcraft.epsilon.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class EpsilonUiModule extends AbstractEpsilonUiModule {
}
