/*
 * generated by Xtext 2.20.0
 */
package de.grammarcraft.epsilon.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.grammarcraft.epsilon.EpsilonRuntimeModule;
import de.grammarcraft.epsilon.EpsilonStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EpsilonIdeSetup extends EpsilonStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EpsilonRuntimeModule(), new EpsilonIdeModule()));
	}
	
}
