/*
 * generated by Xtext 2.20.0
 */
package de.grammarcraft.epsilon.validation;

import java.util.List;

import org.eclipse.emf.common.util.Diagnostic;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.CheckType;

import com.google.inject.Inject;

import de.grammarcraft.epsilon.epsilon.EpsilonPackage;
import de.grammarcraft.epsilon.epsilon.Specification;
import de.grammarcraft.epsilon.validation.EpsilonExecutor.EpsilonIssue;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class EpsilonValidator extends AbstractEpsilonValidator {
	
	@Inject IssuePositionHelper issuePosHelper;
	
	protected static String ISSUE_CODE_PREFIX = "de.grammarcraft.epsilon.";
	public static String EPSILON_COMPILER_GENERATOR_DETECTED_ISSUE = ISSUE_CODE_PREFIX + "EpsilonCGIssue";

	// perform this check only on file save
	@Check(CheckType.NORMAL)
	public void runEpsilonExecutable(Specification specification) {
			boolean isLinux = System.getProperty("os.name").toLowerCase().startsWith("linux");
			if (isLinux) {
				List<EpsilonIssue> issues = EpsilonExecutor.executeOn(specification);
				addMarkersForIssues(specification.eResource(), issues);
			}
			else
				info("Runnig the epsilon compiler generator under Windows is not supported yet, unfortunately. "
						+ "So, the correctness of some affix paramters could not be checked.",
						EpsilonPackage.eINSTANCE.getSpecification_Rules());
	}
	
	private void addMarkersForIssues(Resource resource, List<EpsilonIssue> issues) {
		issues.stream()
			.filter(issue -> issue.getSeverity() != Diagnostic.OK)
			.forEach(issue -> {
				switch (issue.getSeverity()) {
				case Diagnostic.ERROR:
					if (issue.getOffset().isEmpty())						
						error(issue.getMessage(), EpsilonPackage.eINSTANCE.getSpecification_Rules(),
								EPSILON_COMPILER_GENERATOR_DETECTED_ISSUE);
					else {
						EObject relevantElement = issuePosHelper.getElementAtOffset((org.eclipse.xtext.resource.XtextResource)resource, issue);
						error(issue.getMessage(), relevantElement, null, EPSILON_COMPILER_GENERATOR_DETECTED_ISSUE);
					}
					break;
				case Diagnostic.WARNING:
					if (issue.getOffset().isEmpty())						
						warning(issue.getMessage(), EpsilonPackage.eINSTANCE.getSpecification_Rules(),
								EPSILON_COMPILER_GENERATOR_DETECTED_ISSUE);
					else {
						EObject relevantElement = issuePosHelper.getElementAtOffset((org.eclipse.xtext.resource.XtextResource)resource, issue);
						warning(issue.getMessage(), relevantElement, null, EPSILON_COMPILER_GENERATOR_DETECTED_ISSUE);
					}
					break;
				default:
					break;
				}
			});
	}

}
