/*
 * generated by Xtext 2.20.0
 */
package de.grammarcraft.epsilon;

import org.eclipse.xtext.scoping.IGlobalScopeProvider;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.eclipse.xtext.scoping.impl.SimpleLocalScopeProvider;

import com.google.inject.Binder;
import com.google.inject.name.Names;

import de.grammarcraft.epsilon.scoping.DisabledGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EpsilonRuntimeModule extends AbstractEpsilonRuntimeModule {

	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return DisabledGlobalScopeProvider.class;
	}

	public void configureIScopeProviderDelegate(Binder binder) {
		binder.bind(IScopeProvider.class).annotatedWith(Names.named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE))
			.to(SimpleLocalScopeProvider.class);
	}

}
