/*
 * generated by Xtext 2.21.0
 */
package de.grammarcraft.epsilon


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EpsilonStandaloneSetup extends EpsilonStandaloneSetupGenerated {

	def static void doSetup() {
		new EpsilonStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
