/*
 * generated by Xtext 2.21.0
 */
package de.grammarcraft.epsilon.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class EpsilonWebModule extends AbstractEpsilonWebModule {
}
