/*
 * generated by Xtext 2.20.0
 */
package de.grammarcraft.epsilon.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class EpsilonWebModule extends AbstractEpsilonWebModule {
}
