/*
 * generated by Xtext 2.20.0
 */
package de.grammarcraft.epsilon.ui.labeling;

import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

import de.grammarcraft.epsilon.epsilon.MetaRule;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class EpsilonDescriptionLabelProvider extends DefaultDescriptionLabelProvider {

	// Labels and icons can be computed like this:
	
	public String text(IEObjectDescription ele) {
		return ele.getName().toString();
	}
	 
	public String image(IEObjectDescription ele) {
		if (MetaRule.class.getSimpleName().equals(ele.getClass().getName()))
			return "meta.gif";
		else // if (HyperRule.class.getSimpleName().equals(ele.getClass().getName())) {
			return "hyper.gif";
	}
	
}
