/*
 * generated by Xtext 2.20.0
 */
package de.grammarcraft.epsilon.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

import de.grammarcraft.epsilon.epsilon.HyperRule;
import de.grammarcraft.epsilon.epsilon.MetaRule;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class EpsilonLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public EpsilonLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	String image(HyperRule element) {
		return "hyper.gif";
	}

	String image(MetaRule element) {
		return "meta.gif";
	}
}
