name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Download Gamma release artifact files
        uses: robinraju/release-downloader@v1.9
        with:
          repository: "kuniss/gamma"
          tag: "v0.3.0-delta.4"
          fileName: "gamma.*"
          zipBall: true
          out-file-path: "build/gamma-release-download"
      - name: List downloaded Gamma release artifact files
        run: |
          ls -al ${{ github.workspace }}/build/gamma-release-download
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -PgammaReleaseVersion=v0.3.0-delta.4
      - name: Store HTML test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report-html
          path: "**/reports/tests/"
      - name: Store XML test report
        uses: actions/upload-artifact@v3
        with:
          name: test-results-xml
          path: "**/test-results/"
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "**/test-results/**/*.xml"
