name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Release
        uses: gradle/actions/setup-gradle@v3
        env:
          MSVSX_ACCESS_TOKEN: ${{ secrets.MSVSX_ACCESS_TOKEN }}
          OPENVSX_ACCESS_TOKEN: ${{ secrets.OPENVSX_ACCESS_TOKEN }}
        with: 
          arguments: publishToVSMarketplace publishToOpenVSXRegistry
